### PR TITLE
Feature - I18n translate files and add helper wrapper to labels

### LINKED ISSUE #23: Multi language
**Is your feature request related to a problem? Please describe.**
Added possibility for support multi language

**Describe the solution you'd like**
Use i18n from quasar [https://quasar.dev/options/app-internationalization](https://quasar.dev/options/app-internationalization)

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

### PR DESCRIPTION
**Pull request by lewandy**
### General

- I18n translate files to spanish

.

### Type

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature

### Describe the changes here (summarized)

Closes #23

### CODE REVIEW

**Review by Jadhielv — APPROVED** [review]
LGTM @itsalb3rt

**Comment by Jadhielv** [comment]
Btw, @lewandy please, resolve those conflicts and commit to your branch.

**Comment by lewandy** [comment]
@Jadhielv I just resolved the conflicts, you can review again.

**Comment by Jadhielv** [comment]
Perfect! xD. Still waiting approval of @itsalb3rt

**Review by itsalb3rt — APPROVED** [review]
image

**Pull request merged**
