### PR TITLE
Add maxlength in form fields

### LINKED ISSUE #44: Set maximum characters for fields in the visit registration form
**Is your feature request related to a problem? Please describe.**
Set max length in form fields.

**Describe the solution you'd like**

Code Visitor and Receiver: **30**
For a full name Visitor and Receiver: **70**
Title/Position: **150**
Reason for visit: **256**

:warning: If you consider that any of the fields should be lower or higher, please let me know in a comment before applying anything outside of these instructions.

Helps links: [What is a reasonable length limit on person “Name” fields?
](https://stackoverflow.com/q/30485/8009061)

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

### PR DESCRIPTION
**Pull request by Jadhielv**
### General
- maxlength prop form fields

### Type

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Fix #44
- [ ] Feature

### CODE REVIEW

**Review by lewandy — APPROVED** [review]
Nice!, can be merged. 👍🏼

**Comment by itsalb3rt** [comment]
@Jadhielv Please resolve the conflicts, these are generated by the most recent pull request #43

**Comment by Jadhielv** [comment]
Done @itsalb3rt. Btw, @lewandy  please take a look.

**Review by lewandy — APPROVED** [review]

**Review by itsalb3rt — APPROVED** [review]

**Pull request merged**
