### PR TITLE
Create layout drawer

### LINKED ISSUE #58: Navbar options are not available on small screens
**Describe the bug**
Navbar options are not available on small screens

image

### PR DESCRIPTION
**Pull request by Jadhielv**
### General
- Fixed form to center, version mobile.
- Created DesktopScreenToolbar component.
- Created MobileScreenToolbar component.

### Type

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Fix #58
- [x] Feature

**Visits Form on Mobile**

visits-form-mobile

**Layout Drawer**

layout-drawer

### CODE REVIEW

**Comment by itsalb3rt** [comment]
Please keep the original desktop toolbar version, since a national company is using this project and this would mean a radical change

**Comment by Jadhielv** [comment]
Done @itsalb3rt

**Review by lewandy — APPROVED** [review]

**Comment by itsalb3rt** [comment]
Set a default value for language option, when user enter for first time the option keep "empty" and only show the globe icon. 

Screenshot_20201011-154704_Chrome

**Comment by Jadhielv** [comment]
Done @itsalb3rt

**Review by itsalb3rt — APPROVED** [review]
Cool!!

**Pull request merged**
